[server]
headless = true
enableCORS = false
port = 8501

[theme]
base = "light"
primaryColor = "#1E90FF"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#262730"
font = "sans serif"
